#!/bin/bash
# Submission script for dragon2
#SBATCH --job-name=pls_last
#SBATCH --time=0-03:00:00 # hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=16000
#SBATCH --partition=batch
#
#SBATCH --mail-user=anthony.tedde@doct.uliege.be
#SBATCH --mail-type=ALL
#
#SBATCH --comment=pls_last
#
#SBATCH --output=pls_last

srun Rscript ~/workspace/BWchange/03.Calibration/pls_last.R
