#!/bin/bash
# Submission script for dragon2
#SBATCH --job-name=run_tidy_run_all
#SBATCH --time=1-00:00:00 # hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=16000
#SBATCH --partition=batch
#
#SBATCH --mail-user=anthony.tedde@doct.uliege.be
#SBATCH --mail-type=ALL
#
#SBATCH --comment=run_tidy_run_all
#
#SBATCH --output=run_tidy_run_all

srun Rscript ~/workspace/BWchange/03.Calibration/tidy_models/run/run_all.R
