#!/bin/bash
# Submission script for dragon2
#SBATCH --job-name=run_tidy_svm_poly_cor
#SBATCH --time=0-00:20:00 # hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=4000
#SBATCH --partition=batch
#
#SBATCH --mail-user=anthony.tedde@doct.uliege.be
#SBATCH --mail-type=ALL
#
#SBATCH --comment=run_tidy_svm_poly_cor
#
#SBATCH --output=run_tidy_svm_poly_cor

srun Rscript ~/workspace/BWchange/03.Calibration/tidy_svm_poly_cor.R
