#!/bin/bash
# Submission script for dragon2
#SBATCH --job-name=run_tidy_spec_all
#SBATCH --time=0-01:00:00 # hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000
#SBATCH --partition=batch
#
#SBATCH --mail-user=anthony.tedde@doct.uliege.be
#SBATCH --mail-type=ALL
#
#SBATCH --comment=run_tidy_spec_all
#
#SBATCH --output=run_tidy_spec_all

srun Rscript ~/workspace/BWchange/03.Calibration/tidy_models/specifications/recipes_spec.R
srun Rscript ~/workspace/BWchange/03.Calibration/tidy_models/specifications/models_spec.R
srun Rscript ~/workspace/BWchange/03.Calibration/tidy_models/specifications/workflows_spec.R
